### ISSUE TITLE
Wider resolutions create disconnects between field labels and their inputs

### ISSUE THREAD

**Issue by dth1692** [chnm/Datascribe-module#49]
The check box is very far away in comparison to other boxes.

![Check box](https://user-images.githubusercontent.com/35391752/85647746-295ef180-b66d-11ea-8584-2c923728b8dc.JPG)

**Comment by kimisgold** [comment]
Is your browser window particularly wide in this screenshot? I ask because I don't see the 'Reset value' checkbox that should be at the end of the second row. Checkboxes should typically align with the other inputs with the exception of those within the row of common form elements. 

![Screen Shot 2020-06-25 at 9 21 58 AM](https://user-images.githubusercontent.com/606764/85728558-09a7e780-b6c6-11ea-92d0-89e9df7b6740.png)

**Comment by dth1692** [comment]
Yes- full screen.  Seeing it with the line you added makes sense now.  Since this was broken up by a field heading and directly above the common field elements,   I didn't connect it to the other input options.

**Comment by kimisgold** [comment]
Okay, that makes sense. This isn't a bug, but I do think there need to be styles for large resolutions to avoid this kind of visual confusion and make better use of the horizontal space. I'm going to rename the issue to that effect.

**Comment by kimisgold** [comment]
In review, the main concern was the possibility that a map/geolocation input would benefit from the form inputs having a larger maximum width. We're happy with the solution in 48678f0 for the time being.
