### ISSUE TITLE
Previous records table does not scroll (on purpose?)

### ISSUE THREAD

**Issue by mebrett** [chnm/Datascribe-module#53]
The previous records table seems to be limited to the ten previous records before the one you're adding. However, there's no way to scroll down to the form when looking at previous records.

So - is the no-scroll for the tables a purposeful choice? Do we want people to have to toggle between seeing previous records and doing data entry?

Just one previous record:
<img width="810" alt="Screen Shot 2020-06-29 at 11 54 23 AM" src="https://user-images.githubusercontent.com/2314070/86027979-54479d80-b9ff-11ea-910a-c00bb987abfb.png">

At least 10 previous records:
<img width="827" alt="Screen Shot 2020-06-29 at 11 48 46 AM" src="https://user-images.githubusercontent.com/2314070/86028000-5c074200-b9ff-11ea-88a8-41ed917d03af.png">

**Comment by jimsafley** [comment]
I think this regression happened after I increased the limit from 4 to 10 rows. We have the option to fix this behavior, or return to 4 rows and forget about it. I prefer we find a way to fix it.

**Comment by kimisgold** [comment]
The form was set up so that the user could scroll through previous and next record rows easily while editing the current record. The limit on scrolling was to prevent the current record form from disappearing off the screen if there were many previous record rows, as well as to allow the user to see early rows simultaneously as the current record form.

My solution in https://github.com/chnm/Datascribe-module/commit/0655d99fa029468193a8a99f70aa3d3b5dcd0a3a was to put a maximum height on the previous and next record row tables. This should allow the user to see the current record in context of many other records.
