### ISSUE TITLE
Tabbing not fully scrolling page

### ISSUE THREAD

**Issue by jmotis** [chnm/Datascribe-module#63]
In focus mode, Safari, when I tab through the fields to enter data, the fields don't fully scroll so that the field I'm working in is actually only partially displayed on the bottom of the page. It's functional, but looks wrong.

![tabbing-not-fulling-scrolling](https://user-images.githubusercontent.com/8195932/89039392-fc5aca00-d30f-11ea-8bf0-6ed6227ce432.png)

**Comment by lmullen** [comment]
From meeting: Add to top button at the bottom of the form.

**Comment by kimisgold** [comment]
I've drafted the "back to top" button on the dataset form builder form on the `back-to-top`. If it looks good to everyone, I'll implement it on all the other forms.

**Comment by kimisgold** [comment]
Just to note our logic getting from the original issue topic to the current solution: form elements throughout Omeka don't always fully scroll into view upon focus due to the way the window interacts with padding and margins. Jessica discussed that the main want here is a more obvious indicator of where the form ends. A "back to top" button suits this nicely, while also allowing the user to return to the beginning to review their work upon form completion.

**Comment by kimisgold** [comment]
I'd like to get some eyes on this. Could we switch to the `back-to-top` branch on the shared install, @mebrett? If another feature is still getting tested now, maybe we could try on @jmotis's reclaim install.

**Comment by kimisgold** [comment]
Impressions from the meeting: back to top generally looks okay, though I need to look more closely at tabbing order. Focus went from the last form element to the sidebar drawer and add data type buttons instead of the back to top button.

**Comment by kimisgold** [comment]
At the moment, the logic I'm using for inclusion of the "back to top" pattern is to use it on forms that could grow to over 5+ fields. This mainly applies to the form builder and the record forms. I'm happy to apply it in other contexts if others think it would help; at the moment, it looks a little silly in places that don't produce a scrollbar on a laptop resolution, which is most of the other forms in the module.
