### ISSUE TITLE
Redirection after approving an item

### ISSUE THREAD

**Issue by lmullen** [chnm/Datascribe-module#79]
A current workflow might look something like this:

A reviewer navigates to the items to be reviewed from the dashboard. The reviewer looks at one closely by looking at the record show page, then saves the item as newly approved. 

If I'm not mistaken, the reviewer is then redirected to the general DataScribe items browse, not to the items to be approved browse. Might it be better for them to be sent to the records to be approved page?

**Comment by jimsafley** [comment]
The problem with automatic redirects like this is that not all workflows are the same. The reviewer could be coming into the review process any number of ways. Could we safely assume that most or all reviewers will want to automatically return to the "All items that need review" filter, on page 1, with the default sorting? If so, it's trivial to implement.

Another possibility: instead of redirecting, we could add a quick link to the success message. Something like: "Item successfully updated and marked as approved. [View all items that need review.]()" A downside is it adds one more step to the workflow.

**Comment by lmullen** [comment]
Right. I understand the problem with assuming that all users want to do the same thing next.

I think the "View all items that need review" is a great idea. It doesn't make an unwarranted assumption. But also it means that the user doesn't have to think about how to get back to the all items to review. It is an extra click, but not any extra thinking.
