### ISSUE TITLE
Testing: Batch edit record values

### ISSUE THREAD

**Issue by jimsafley** [chnm/Datascribe-module#8]
The [record-batch-edit](https://github.com/chnm/Datascribe-module/tree/record-batch-edit) branch introduces the ability for reviewers to batch edit record values. On the record browse page, the "Edit selected" and "Edit all" batch actions should take you to a page that now renders a record form that's modified for bulk data entry. You should be able to bulk-mark values as missing and illegible; and you should be able to bulk-edit the values themselves, using the same form elements used in the normal record add/edit pages. The one necessary difference is that you have to flag intent to edit a particular value by checking "Edit value?"

**Comment by mebrett** [comment]
If I'm looking at one item, and I select "edit all", it apparently edits all the items in the dataset, not just the ones in the item? But the header still says the name of the item from which I accessed the Batch edit form. 

Here's the item, it has three records:
<img width="627" alt="Screen Shot 2020-03-30 at 11 02 49 AM" src="https://user-images.githubusercontent.com/2314070/77928201-2030d500-7276-11ea-8e73-abfc453acbd1.png">

And the batch edit form:
<img width="1155" alt="Screen Shot 2020-03-30 at 11 03 03 AM" src="https://user-images.githubusercontent.com/2314070/77928279-38085900-7276-11ea-8b4c-f1fc41b5603b.png">

If the "edit all" option does in fact edit everything in the *dataset* rather than the *item* that should be clearer on the form.

**Comment by jimsafley** [comment]
Good catch. It should be fixed now.

**Comment by mebrett** [comment]
Yes - now when I Edit All, it only edits the records for that item.
