### ISSUE TITLE
Approval extends to new records 

### ISSUE THREAD

**Issue by mebrett** [chnm/Datascribe-module#82]
If you add a record to an item after the item has been approved, that record is automatically added to the export CSV, without running a new export and without having to be approved first. 

While locking an item might help, I think that admins can still edit locked items anyway. So it might be worth exploring whether the export can disregard any new records since the item was last approved or the dataset was last exported.

**Comment by jmotis** [comment]
Possible solution: when a new record is added to an approved item, it unapproves the item. Would want to have a warning, if possible, to let them know that adding the record will unapprove the item.

**Comment by jimsafley** [comment]
I should note that a transcriber cannot add a new record to an approved item. Shouldn't there be an expectation that if a _reviewer_ adds a new record, the record is approved by default?

**Comment by jmotis** [comment]
It depends on how the project team is using the review function. Are they using it to ensure a certain group of transcribers always have oversight or are they using it to make sure that all transcriptions have a second pair of eyes on them before approval? I think both are valid workflows that a team might choose.

**Comment by jimsafley** [comment]
The reviewer who added (or modified) a record could always change the status of the item themselves, depending on whatever workflow was established for the project. Maybe this could be solved at the organizational level?

Even so, should we add a configuration that gives administrators the option to make this workflow automatic, what review status should the item revert to? Not reviewed? Not approved? I lean toward "not reviewed" because "not approved" would shift the work back to the transcriber, who had nothing to do with the added/modified record.

**Comment by jmotis** [comment]
Yes, if we were going to change the status I agree it should be not reviewed (because the new addition was not reviewed). I'm going to ping a few people via Slack who have been working on multi-record items and see what they think (configuration option? just a warning alert? some other thing?) and will report back.
