### ISSUE TITLE
Break item filter in dataset into submenu

### ISSUE THREAD

**Issue by mebrett** [chnm/Datascribe-module#93]
Break out the filter so that there is one dropdown for "all items/locked to me/unlocked" etc and then another for priority etc.

**Comment by jimsafley** [comment]
For the two dropdowns, would you mind listing the filters in the order you want?

- All items that are not approved
- All items that are approved
- All items that need review
- All items that need initial review
- All items that need re-review
- Items with values marked as invalid
- Items I reviewed that need re-review
- Items I reviewed that are not approved
- Items I reviewed that are approved
- All prioritized items
- All unlocked and new items
- All unlocked and in progress items
- My new items
- My in progress items
- My items that need review
- My items that are not approved
- My items that are approved

**Comment by mebrett** [comment]
My suggestion would be to set them up like this.

Dropdown one:
- All items
- All unlocked items
- All locked items
- Items locked to me
- Items I reviewed

Dropdown two:
- in progress
- not approved
- approved
- need review
- need re-review
- with invalid values

@jmotis @hepplerj Thoughts?

**Comment by jimsafley** [comment]
You're missing a few filters there, and there's some ambiguity. I strongly prefer that we use the existing filters and not create new ones. It's fine to rename the existing filters, but only if they convey the same idea.

**Comment by jmotis** [comment]
I started playing around with the list and realized that if we go for a strict dropdown one/two list that might lead us to creating a lot of new filters. While I like the idea of being able to find all locked items (as I was realizing earlier today it's not super easy to find that from our existing structure) I otherwise think our existing filter set is pretty solid, and obviously the search feature will solve a lot of edge cases for filtering. 

How hard is it to use submenus to create something where you could either select the top level menu item or an item from a submenu, like:

- All items
  - prioritized items
  - unlocked and new items
  - unlocked and in progress items
  - not approved
  - approved
- Items that need review
  - initial review
  - re-review
  - with values marked as invalid
- Items I reviewed
  - need re-review
  - not approved
  - approved
- My items (locked to me)
  - new items
  - in progress items
  - items that need review
  - items that are not approved
  - items that are approved

That way, when you go to the menu to start, you see:
- All items
- Items that need review
- Items I reviewed
- My items (locked to me)
then can go into the submenus from there

(This is my first thoughts/gut instinct on reordering, I'm not sold on this as the be-all end-all.)

**Comment by mebrett** [comment]
Jim's pull request would replace the current version: 
![One long menu with many options](https://user-images.githubusercontent.com/2314070/148963832-233105f3-0eee-4c63-9315-441f6e0bbc32.png)

with this
<img width="376" alt="menu with subheadings as proposed upthread" src="https://user-images.githubusercontent.com/2314070/148963981-e89407d9-e51a-4311-8bb1-afbc4187422d.png">

**Comment by jmotis** [comment]
That's definitely much more legible from my perspective. Just that little bit of chunking makes a huge difference. Moving the all items grouping to the bottom makes sense to me.

**Comment by mebrett** [comment]
Agreed. I'll merge this into beta-feedback
